# Generated by Django 4.1.3 on 2022-11-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(height_field='100', upload_to='photos', width_field='100'),
        ),
    ]
